name: fit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  # - openai>=1.0.0
  # - altair==4.1.0
  # - gspread==5.6.2
  # - gspread_dataframe==3.3.0
  # - numpy==1.23.3
  # - pandas
  # - plotly
  # - pytest
  # - streamlit
  # - duckdb
